spring:
  application:
    name: catalog

  datasource:
    url: jdbc:postgresql://localhost:5432/ecomapp?currentSchema=catalog
    username: postgres
    password: ckfdenfnjgdkj
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: order-events-listener-group
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

custom:
  page:
    default-size: 10
  strategy:
    popularity:
      item-is-considered-popular-at-orders-count: 25
    shoes-size:
      min: 30
      max: 46
  category:
    img-path-prefix:
      men: catalog/src/main/resources/images/category/men/
      women: catalog/src/main/resources/images/category/women/

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    enabled: false

server:
  port: 8000
  servlet:
    context-path: /catalog

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
